#include "apollonian.hpp"

namespace apollonian {

const ApollonianState ApollonianState::identity(
        MobiusTransformation::identity,
        Permutation<4>::identity);

/* The "canonical" Apollonian gasket is the limit set of the monoid
 * generated by the following four transformations.  The first three are
 * parabolic, while the fourth is an involution.
 *
 * The three parabolic transformations generate an "Apollonian
 * triangle," which is the intersection of the full gasket with one of
 * the two connected components of the complement of the three mutually
 * tangent disks that start the process.
 *
 * The last involution swaps the two Apollonian triangles that comprise
 * the full gasket.
 */

/* Parabolic: z -> z + i */
const ApollonianState ApollonianState::m0{{1,    1i,
                                           0,  1   },
                                          {3, 1, 2, 0}};

/* Parabolic: z -> z/(1 - i*z) */
const ApollonianState ApollonianState::m1{{ 1,    0,
                                             -1i, 1},
                                          {0, 3, 2, 1}};

/* Parabolic: z -> ((1-i)*z + i)/(-i*z + 1+i) */
const ApollonianState ApollonianState::m2{{1.0-1i,     1i,
                                              -1i, 1.0+1i},
                                          {0, 1, 3, 2}};

/* Involution: z -> 1 - z */
const ApollonianState ApollonianState::inv{{ -1i, 1i,
                                               0, 1i},
                                           {0, 2, 1, 3}};

/* These are the four mutually tangent disks whose orbits under the
 * monoid generated above cover the complement of the canonical
 * Apollonian gasket.
 */

/* real(z) >= 1 */
const Circle ApollonianState::c0{0, -1,
                                     2};

/* |z - 0.5| <= 0.5 */
const Circle ApollonianState::c1{2, -1,
                                     0};

/* real(z) <= 0 */
const Circle ApollonianState::c2{0, 1,
                                    0};

/* |z - (0.5 + 0.5i)| <= 0.5 */
const Circle ApollonianState::c3{2.0, -1.0-2i,
                                       2.0};

} // apollonian
